print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/paulmallon/Desktop/Santak/Assets/thePlayerModelCircle.ma"`)
{		
	file -o "/Users/paulmallon/Desktop/Santak/Assets/thePlayerModelCircle.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/paulmallon/Desktop/Santak/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/paulmallon/Desktop/Santak/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/paulmallon/Desktop/Santak/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
